name: Docker Build and Push

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Harbor certificate
      run: |
        sudo mkdir -p /etc/ssl/certs
        echo "${{ secrets.HARBOR_CERT }}" > sudo /etc/ssl/certs/harbor.crt
        sudo update-ca-certificates


    - name: Login to Harbor
      uses: docker/login-action@v2
      with:
        registry: 192.168.2.76:443
        username: admin
        password: Harbor12345

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: 192.168.2.76:443/hama/hama-image-upload:${{ github.sha }}
        cache-from: type=registry,ref=192.168.2.76:443/hama/hama-image-upload:latest
        cache-to: type=inline
